name: SailboatRadio
attributes:
  ORGANIZATIONNAME: Sailboat Technologies, Inc.
options:
  bundleIdPrefix: d.mazo
targets:
  SailboatRadio:
    scheme:
      testTargets:
        - SailboatRadioTests
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    name: SailboatRadio
    sources:
        - path: SailboatRadio/Sources
          buildPhase: sources
          name: SailboatRadio
        - path: ../assets/Assets.xcassets
          buildPhase: sources
    dependencies:
      - framework: sailboatMedia/SailboatMedia.framework
    settings:
      configs:
        debug:
          CUSTOM_BUILD_SETTING: 1.0
        release:
          CUSTOM_BUILD_SETTING: 1.0
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "sailboat.radio.app"
        INFOPLIST_FILE: "SailboatRadio/Info.plist"
        TARGETED_DEVICE_FAMILY: [1, 2]

  SailboatRadioTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SailboatRadioTests
    dependencies:
      - target: SailboatRadio